### ISSUE TITLE
Output widget + multithread weirdness

### ISSUE THREAD

**Issue by wolfv** [QuantStack/xeus-python#95]
When using output widgets and adding data from multiple threads, xeus-python doesn't seem to properly update the contents of the output widget. Only upon triggering the kernel from the frontend (e.g. by activating auto-completion or executing a `print` statement) the contents of the output widget get updated.

I am using the following output redirector:

```py
import threading
import ipywidgets as widgets
import sys

output_registry = {}

class OutputRedirector:
    def __init__(self, original):
        self.original = original
    
    def write(self, msg):
        thread_name = threading.currentThread().name
        if thread_name != 'MainThread':
            output_registry[threading.currentThread().getName()].append_stdout(msg)
        else:
            self.original.write(msg)

    def flush(self):
        self.original.flush()

    # necessary for ipython, but **not** for xeus-python!
    def set_parent(self, parent):
        self.original.set_parent(parent)

sys.stdout = OutputRedirector(sys.stdout)
```

And now you can create a new thread with outptu widget, e.g. 

```py
def func():
    while True:
        print("Hello?")

def new_thread():
    output_registry['test'] = widgets.Output()
    thread = threading.Thread(target=func, name="test")
    thread.start()
    return output_registry['test']
```

**Comment by martinRenou** [comment]
As per in-person discussion, we found out that it's actually the way `xeus` messaging is implemented which makes Python multi-threading not working.

Little code snippet for reproducing the issue:
```python
import threading
def tfunc():
    i = 0
    while True:
        i += 1
        print(i)
t = threading.Thread(target=tfunc)
t.start()
```
This results in:
![multithreading](https://user-images.githubusercontent.com/21197331/55627349-3ebcd700-57ae-11e9-9616-1bdf8caafd9c.png)

As we can see from the screenshot, the secondary thread is completely blocked between two messages. This is due to the way `xeus` waits for incoming messages from the client:
https://github.com/QuantStack/xeus/blob/0.19.1/src/xserver_zmq.cpp#L80-L83

The `poll(-1)` is a blocking call, meaning that the code is blocked until there is an incoming message from the client (execute request, complete request...).
Python threads not being real system threads, it means that they are also stopped when no Python code is executed. Resulting in Python threads being completely stopped between two messages.

I see three ways of fixing this issue:
1. The easy way:
We implement a `server` class in xeus-python, inheriting from `xeus::xserver_zmq` that reimplement the `start_impl` method that would call `poll` in an non-blocking fashion and a Python `sleep` function allowing Python threads to resume their job. Something like:
```c++
void server::start_impl(zmq::multipart_t& message)
{
    start_publisher_thread();
    start_heartbeat_thread();

    m_request_stop = false;

    publish(message);

    while (!m_request_stop)
    {
        zmq::pollitem_t items[]
            = { { m_controller, 0, ZMQ_POLLIN, 0 }, { m_shell, 0, ZMQ_POLLIN, 0 } };

        int nb_msg = zmq::poll(&items[0], 2, 0); // Non-blocking call
        if (nb_msg > 0)
        {
            // process messages
        }
        else
        {
             // Wait a bit in Python allowing Python threads to resume their job
             py::module::import("time").attr("sleep")(0.02);
        }
    }

    stop_channels();

    std::exit(0);
}
```

2. The medium hard way (not sure this one would work but I guess we can try):
We wrap the `xserver_zmq::poll` call inside of a Python function using pybind11. Meaning that the `poll` function is called from Python, which would allow Python threads to keep on working?

3. The hard way:
We put the Python interpreter logic in a real system thread driven from C++. This would allow Python threads to continue their job while the C++ kernel logic is waiting for messages.
This is hard for the simple reason that it would need (a lot of?) modifications in `xeus`. Python interpreter logic being in an other thread, I guess the execution logic would become asynchronous, which is not currently the case in `xeus`.
