### ISSUE TITLE
Dropping Python 2 support?

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/xeus-python#97]
What if we drop Python 2 support? That would remove some code

**Comment by pmav99** [comment]
Just my 2 cents: 

Python 2 is probably going to be relevant for several years more (e.g. it will be supported by ubuntu 18.04) but I seriously doubt that more than a handful of new projects are being written in Python 2. Since xeus-python is not that big yet + existing projects are unlikely to switch from ipython until it becomes big, it might not be a bad idea to drop python 2 and focus on Python 3, especially if that simplifies the code.

**Comment by martinRenou** [comment]
I agree with you.
But thinking about it, I don't think we want to see users opening issues on the repo saying "Hey! it does not work with my Notebook" just because they did not update their notebook to Python 3.
So yeah I guess we should live with the workarounds we have for supporting Python 2.
